version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y docker.io
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x8k4k2w6
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URI:$DOCKER_IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:$DOCKER_IMAGE_TAG

artifacts:
  files:
    - '**/*'
